# Generated by Django 5.1 on 2024-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Engineering', 'Engineering'), ('Food', 'Food'), ('Art', 'Art')], max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('rating', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
            ],
        ),
    ]
